stages:
  - build
  # - test
  - deploy

image: 'ruby:2.6.3'
services:
  - postgres:latest

variables:
  POSTGRES_DB: expedition_tracker

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

build:
  - bundle install -j $(nproc) --path vendor # Install dependencies into ./vendor/ruby

# test:
#   variables:
#     DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB'
#   script:
#     - bundle exec rspec spec
#   only:
#     - master

# rails:
#   variables:
#     DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB'
#   script:
#     - bundle exec rails db:migrate
#     - bundle exec rails db:seed
#   only:
#     - master

deploy_staging:
  type: deploy
  environment: production
  script:
    - echo "Deploy to staging server"
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
  only:
    - master
